name: Atualizar atividade no README

on:
  push:
    branches: ['main']   # ajuste se sua branch principal for outra
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Atualizar atividade recente
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          COMMIT_MSG: "chore: atualiza atividade recente"
          MAX_LINES: 10
          TARGET: "README.md"
          # timezone opcional, ex.: America/Sao_Paulo
